s='hEllO cLasS'
print(s.lower())
print(s.upper())
print(s.title())
print(s.capitalize())
print(s.swapcase())
print(s.count('e'))
print(s.count('E'))
print(s.count('s',5))
print(s.find('s'))
print(s.find('o'))
print(s.index('E'))
print(s.rstrip('s'))
print(s.lstrip('h'))
print(s.lstrip('E'))

