l1=float(input("enter length of floor="))
b1=float(input("enter breadth of floor="))
l2=float(input("enter length of tiles="))
b2=float(input("enter breadth of tiles="))
print("number of tiles required to cover up the floor=",(l1*b1)/(l2*b2))
